wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1712080276
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
allpick:
  desc: null
  value: false
config:
  desc: null
  value: DVC_1024.json
log:
  desc: null
  value: ''
pretrain:
  desc: null
  value: ''
rerank:
  desc: null
  value: false
test:
  desc: null
  value: false
testauc:
  desc: null
  value: false
testhevc:
  desc: null
  value: false
testmcl:
  desc: null
  value: false
testvtl:
  desc: null
  value: false
